name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Triggers deployment whenever there's a push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Adjust Node.js version if necessary

      - name: Install dependencies
        run: npm install
        working-directory: eagle-task

      - name: Build the project
        run: CI='' npm run build # Suppresses warnings as errors
        working-directory: eagle-task

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: eagle-task/build # Path to the build output directory
